using Generated.Settings;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

var inputPath = args.Length >= 1 ? args[0] : "settings-uris.json";
var outputDir = args.Length >= 2 ? args[1] : "generated";

Directory.CreateDirectory(outputDir);

var json = await File.ReadAllTextAsync(inputPath, Encoding.UTF8);
var model = JsonSerializer.Deserialize(json, SettingsJsonContext.Default.Root)
    ?? throw new Exception("Failed to parse JSON.");

static string ToPascalIdentifier(string s)
{
    // id は "windows-update" みたいな形を想定
    // 1) 非英数字を空白化 2) 単語結合 3) 先頭が数字なら _ を付ける
    s = Regex.Replace(s, @"[^A-Za-z0-9]+", " ").Trim();
    if (string.IsNullOrWhiteSpace(s)) return "Unknown";

    var parts = s.Split(' ', StringSplitOptions.RemoveEmptyEntries);
    var sb = new StringBuilder();
    foreach (var p in parts)
    {
        var t = p;
        if (t.Length == 0) continue;
        sb.Append(char.ToUpperInvariant(t[0]));
        if (t.Length > 1) sb.Append(t.Substring(1));
    }

    var ident = sb.ToString();
    if (char.IsDigit(ident[0])) ident = "_" + ident;
    return ident;
}

static string EscapeStringLiteral(string s)
{
    // C# string literal 用
    return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

static string SafeConstName(string enumName) => enumName; // 今回は enum 名=const 名で OK

// Collect items
var items = new List<ItemInfo>();
foreach (var cat in model.Categories)
{
    foreach (var item in cat.Items)
    {
        var enumName = ToPascalIdentifier(item.Id);
        items.Add(new ItemInfo(
            CategoryId: cat.Id,
            CategoryName: cat.Name,
            ItemId: item.Id,
            ItemName: item.Name,
            Uri: item.Uri,
            EnumName: enumName
        ));
    }
}

// Ensure uniqueness (enum/const names)
var used = new HashSet<string>(StringComparer.Ordinal);
for (int i = 0; i < items.Count; i++)
{
    var name = items[i].EnumName;
    if (used.Add(name)) continue;

    // 重複したら Category をプレフィックスにする
    var prefixed = ToPascalIdentifier(items[i].CategoryId) + name;
    if (!used.Add(prefixed))
    {
        // それでもダメなら連番
        int n = 2;
        var candidate = prefixed + n;
        while (!used.Add(candidate)) { n++; candidate = prefixed + n; }
        prefixed = candidate;
    }
    items[i] = items[i] with { EnumName = prefixed };
}

// ===== Generate enum =====
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("namespace Generated.Settings;");
    sb.AppendLine();
    sb.AppendLine("public enum SettingsUri");
    sb.AppendLine("{");
    sb.AppendLine("    SettingsHome,");
    sb.AppendLine();

    // カテゴリごとに並べる
    foreach (var g in items.GroupBy(x => x.CategoryName))
    {
        sb.AppendLine($"    // {g.Key}");
        foreach (var it in g)
            sb.AppendLine($"    {it.EnumName},");
        sb.AppendLine();
    }

    sb.AppendLine("}");
    await File.WriteAllTextAsync(Path.Combine(outputDir, "SettingsUri.g.cs"), sb.ToString(), Encoding.UTF8);
}

// ===== Generate const class =====
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("namespace Generated.Settings;");
    sb.AppendLine();
    sb.AppendLine("public static class MsSettingsUris");
    sb.AppendLine("{");
    sb.AppendLine("    public const string SettingsHome = \"ms-settings:\";");
    sb.AppendLine();

    foreach (var g in items.GroupBy(x => x.CategoryName))
    {
        sb.AppendLine($"    // {g.Key}");
        foreach (var it in g)
        {
            var constName = SafeConstName(it.EnumName);
            sb.AppendLine($"    public const string {constName} = \"{EscapeStringLiteral(it.Uri)}\";");
        }
        sb.AppendLine();
    }

    sb.AppendLine("}");
    await File.WriteAllTextAsync(Path.Combine(outputDir, "MsSettingsUris.g.cs"), sb.ToString(), Encoding.UTF8);
}

// ===== Generate ViewModels =====
// WPF 依存を避けたいので INotifyPropertyChanged 最低限だけ同梱。
// すでに CommunityToolkit.Mvvm を使ってるなら差し替え簡単。
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("using System.Collections.ObjectModel;");
    sb.AppendLine();
    sb.AppendLine("namespace Generated.Settings;");
    sb.AppendLine();
    sb.AppendLine("public sealed class SettingsCategoryVm");
    sb.AppendLine("{");
    sb.AppendLine("    public string Id { get; }");
    sb.AppendLine("    public string Name { get; }");
    sb.AppendLine("    public ObservableCollection<SettingsItemVm> Items { get; }");
    sb.AppendLine();
    sb.AppendLine("    public SettingsCategoryVm(string id, string name, ObservableCollection<SettingsItemVm> items)");
    sb.AppendLine("    {");
    sb.AppendLine("        Id = id;");
    sb.AppendLine("        Name = name;");
    sb.AppendLine("        Items = items;");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
    sb.AppendLine("public sealed class SettingsItemVm");
    sb.AppendLine("{");
    sb.AppendLine("    public string Id { get; }");
    sb.AppendLine("    public string Name { get; }");
    sb.AppendLine("    public SettingsUri Key { get; }");
    sb.AppendLine("    public string Uri { get; }");
    sb.AppendLine();
    sb.AppendLine("    public SettingsItemVm(string id, string name, SettingsUri key, string uri)");
    sb.AppendLine("    {");
    sb.AppendLine("        Id = id;");
    sb.AppendLine("        Name = name;");
    sb.AppendLine("        Key = key;");
    sb.AppendLine("        Uri = uri;");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
    sb.AppendLine("public static class SettingsMenuFactory");
    sb.AppendLine("{");
    sb.AppendLine("    public static ObservableCollection<SettingsCategoryVm> CreateDefault()");
    sb.AppendLine("    {");
    sb.AppendLine("        return new ObservableCollection<SettingsCategoryVm>");
    sb.AppendLine("        {");

    foreach (var cat in model.Categories)
    {
        sb.AppendLine($"            new SettingsCategoryVm(");
        sb.AppendLine($"                id: \"{EscapeStringLiteral(cat.Id)}\",");
        sb.AppendLine($"                name: \"{EscapeStringLiteral(cat.Name)}\",");
        sb.AppendLine($"                items: new ObservableCollection<SettingsItemVm>");
        sb.AppendLine("                {");

        foreach (var item in cat.Items)
        {
            var it = items.First(x => x.ItemId == item.Id && x.CategoryId == cat.Id);
            sb.AppendLine("                    new SettingsItemVm(");
            sb.AppendLine($"                        id: \"{EscapeStringLiteral(item.Id)}\",");
            sb.AppendLine($"                        name: \"{EscapeStringLiteral(item.Name)}\",");
            sb.AppendLine($"                        key: SettingsUri.{it.EnumName},");
            sb.AppendLine($"                        uri: \"{EscapeStringLiteral(item.Uri)}\"),");
        }

        sb.AppendLine("                }),");
    }

    sb.AppendLine("        };");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    await File.WriteAllTextAsync(Path.Combine(outputDir, "SettingsMenu.g.cs"), sb.ToString(), Encoding.UTF8);
}

Console.WriteLine($"Generated: {outputDir}");


// ===== JSON DTOs =====
public sealed record Root(List<Category> Categories);
public sealed record Category(string Id, string Name, List<Item> Items);
public sealed record Item(string Id, string Name, string Uri);

public sealed record ItemInfo(
    string CategoryId,
    string CategoryName,
    string ItemId,
    string ItemName,
    string Uri,
    string EnumName
);
